-- MySQL Script generated by MySQL Workbench
-- Fri Jan 31 09:32:09 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hyo_project_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hyo_project_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hyo_project_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `hyo_project_db` ;

-- -----------------------------------------------------
-- Table `hyo_project_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyo_project_db`.`user` ;

CREATE TABLE IF NOT EXISTS `hyo_project_db`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(100) NOT NULL,
  `generation_id` INT NOT NULL,
  `role` VARCHAR(20) NOT NULL DEFAULT 'USER',
  `login_type` VARCHAR(20) NOT NULL,
  `is_ssafy` TINYINT(1) NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `generation_id` (`generation_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hyo_project_db`.`generation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyo_project_db`.`generation` ;

CREATE TABLE IF NOT EXISTS `hyo_project_db`.`generation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` INT NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hyo_project_db`.`algorithm_guide`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyo_project_db`.`algorithm_guide` ;

CREATE TABLE IF NOT EXISTS `hyo_project_db`.`algorithm_guide` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `user_id` INT NOT NULL,
  `generation_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT '0',
  `thumbnail` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `idx_algorithm_guide_search` (`title` ASC, `generation_id` ASC, `created_at` ASC) VISIBLE,
  INDEX `algorithm_guide_ibfk_2` (`generation_id` ASC) VISIBLE,
  CONSTRAINT `algorithm_guide_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `hyo_project_db`.`user` (`id`),
  CONSTRAINT `algorithm_guide_ibfk_2`
    FOREIGN KEY (`generation_id`)
    REFERENCES `hyo_project_db`.`generation` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hyo_project_db`.`algorithm_problem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyo_project_db`.`algorithm_problem` ;

CREATE TABLE IF NOT EXISTS `hyo_project_db`.`algorithm_problem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `user_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT '0',
  `url_deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_active_url` (`url` ASC, `url_deleted_at` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `idx_algorithm_problem_title` (`title` ASC, `created_at` ASC) VISIBLE,
  CONSTRAINT `algorithm_problem_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `hyo_project_db`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 49
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hyo_project_db`.`programming_language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyo_project_db`.`programming_language` ;

CREATE TABLE IF NOT EXISTS `hyo_project_db`.`programming_language` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hyo_project_db`.`algorithm_problem_solution`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyo_project_db`.`algorithm_problem_solution` ;

CREATE TABLE IF NOT EXISTS `hyo_project_db`.`algorithm_problem_solution` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` TEXT NOT NULL,
  `summary` TEXT NOT NULL,
  `content` TEXT NOT NULL,
  `user_id` INT NOT NULL,
  `runtime` INT NULL DEFAULT NULL,
  `memory` INT NULL DEFAULT NULL,
  `language_id` INT NOT NULL,
  `generation_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT '0',
  `problem_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `language_id` (`language_id` ASC) VISIBLE,
  INDEX `idx_algorithm_solution_generation` (`generation_id` ASC, `created_at` ASC) VISIBLE,
  INDEX `idx_algorithm_solution_performance` (`memory` ASC, `runtime` ASC, `created_at` ASC) VISIBLE,
  INDEX `FK_problem_id` (`problem_id` ASC) VISIBLE,
  CONSTRAINT `algorithm_problem_solution_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `hyo_project_db`.`user` (`id`),
  CONSTRAINT `algorithm_problem_solution_ibfk_2`
    FOREIGN KEY (`language_id`)
    REFERENCES `hyo_project_db`.`programming_language` (`id`),
  CONSTRAINT `algorithm_problem_solution_ibfk_3`
    FOREIGN KEY (`generation_id`)
    REFERENCES `hyo_project_db`.`generation` (`id`),
  CONSTRAINT `FK_problem_id`
    FOREIGN KEY (`problem_id`)
    REFERENCES `hyo_project_db`.`algorithm_problem` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 78
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hyo_project_db`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyo_project_db`.`tag` ;

CREATE TABLE IF NOT EXISTS `hyo_project_db`.`tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_tag_name` (`name` ASC) VISIBLE,
  INDEX `idx_tag_name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hyo_project_db`.`algorithm_problem_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyo_project_db`.`algorithm_problem_tag` ;

CREATE TABLE IF NOT EXISTS `hyo_project_db`.`algorithm_problem_tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `algorithm_problem_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_algo_problem_tag` (`algorithm_problem_id` ASC, `tag_id` ASC) VISIBLE,
  INDEX `idx_algorithm_problem_tag_tag` (`tag_id` ASC) VISIBLE,
  CONSTRAINT `algorithm_problem_tag_ibfk_1`
    FOREIGN KEY (`algorithm_problem_id`)
    REFERENCES `hyo_project_db`.`algorithm_problem` (`id`),
  CONSTRAINT `algorithm_problem_tag_ibfk_2`
    FOREIGN KEY (`tag_id`)
    REFERENCES `hyo_project_db`.`tag` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 46
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hyo_project_db`.`bookmark`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyo_project_db`.`bookmark` ;

CREATE TABLE IF NOT EXISTS `hyo_project_db`.`bookmark` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `content_type` ENUM('ALGO_GUIDE', 'ALGO_SOLUTION', 'WEB_GUIDE', 'WEB_RECOMMEND') NOT NULL,
  `content_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_bookmark` (`user_id` ASC, `content_type` ASC, `content_id` ASC) VISIBLE,
  CONSTRAINT `bookmark_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `hyo_project_db`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 136
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hyo_project_db`.`chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyo_project_db`.`chat` ;

CREATE TABLE IF NOT EXISTS `hyo_project_db`.`chat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `user_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sender` VARCHAR(100) NOT NULL,
  `generation_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chat_generation` (`generation_id` ASC) VISIBLE,
  INDEX `chat_ibfk_1` (`user_id` ASC) VISIBLE,
  CONSTRAINT `chat_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `hyo_project_db`.`user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_chat_generation`
    FOREIGN KEY (`generation_id`)
    REFERENCES `hyo_project_db`.`generation` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 407
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hyo_project_db`.`finale_team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyo_project_db`.`finale_team` ;

CREATE TABLE IF NOT EXISTS `hyo_project_db`.`finale_team` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `generation_id` INT NOT NULL,
  `submitted_at` DATE NOT NULL DEFAULT curdate(),
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_final_team_generation` (`generation_id` ASC, `created_at` ASC) VISIBLE,
  CONSTRAINT `finale_team_ibfk_1`
    FOREIGN KEY (`generation_id`)
    REFERENCES `hyo_project_db`.`generation` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hyo_project_db`.`finale_project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyo_project_db`.`finale_project` ;

CREATE TABLE IF NOT EXISTS `hyo_project_db`.`finale_project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `team_id` INT NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `user_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT '0',
  `thumbnail` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `idx_final_project_generation` (`team_id` ASC) VISIBLE,
  CONSTRAINT `finale_project_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `hyo_project_db`.`user` (`id`),
  CONSTRAINT `finale_project_ibfk_2`
    FOREIGN KEY (`team_id`)
    REFERENCES `hyo_project_db`.`finale_team` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hyo_project_db`.`finale_excluded_member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyo_project_db`.`finale_excluded_member` ;

CREATE TABLE IF NOT EXISTS `hyo_project_db`.`finale_excluded_member` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `project_id` (`project_id` ASC) VISIBLE,
  CONSTRAINT `finale_excluded_member_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `hyo_project_db`.`user` (`id`),
  CONSTRAINT `finale_excluded_member_ibfk_2`
    FOREIGN KEY (`project_id`)
    REFERENCES `hyo_project_db`.`finale_project` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hyo_project_db`.`finale_project_board`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyo_project_db`.`finale_project_board` ;

CREATE TABLE IF NOT EXISTS `hyo_project_db`.`finale_project_board` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `finale_project_id` INT NOT NULL,
  `finale_team_id` INT NOT NULL,
  `summary` VARCHAR(255) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `user_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT '0',
  `thumbnail` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `team_id` (`finale_team_id` ASC) VISIBLE,
  INDEX `project_id` (`finale_project_id` ASC) VISIBLE,
  CONSTRAINT `finale_project_board_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `hyo_project_db`.`user` (`id`),
  CONSTRAINT `finale_project_board_ibfk_2`
    FOREIGN KEY (`finale_team_id`)
    REFERENCES `hyo_project_db`.`finale_team` (`id`),
  CONSTRAINT `finale_project_board_ibfk_3`
    FOREIGN KEY (`finale_project_id`)
    REFERENCES `hyo_project_db`.`finale_project` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hyo_project_db`.`finale_team_member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyo_project_db`.`finale_team_member` ;

CREATE TABLE IF NOT EXISTS `hyo_project_db`.`finale_team_member` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `finale_team_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `role` ENUM('LEADER', 'MEMBER') NULL DEFAULT 'MEMBER',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_final_team_member` (`finale_team_id` ASC, `user_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `finale_team_member_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `hyo_project_db`.`user` (`id`),
  CONSTRAINT `fk_finale_team_member_team`
    FOREIGN KEY (`finale_team_id`)
    REFERENCES `hyo_project_db`.`finale_team` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hyo_project_db`.`oauth2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyo_project_db`.`oauth2` ;

CREATE TABLE IF NOT EXISTS `hyo_project_db`.`oauth2` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `provider` VARCHAR(20) NOT NULL,
  `provider_id` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_provider_account` (`provider` ASC, `provider_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `oauth2_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `hyo_project_db`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hyo_project_db`.`project_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyo_project_db`.`project_image` ;

CREATE TABLE IF NOT EXISTS `hyo_project_db`.`project_image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_type` ENUM('track', 'final') NOT NULL,
  `project_id` INT NOT NULL,
  `image_path` VARCHAR(255) NOT NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT '0',
  `created_at` DATE NOT NULL DEFAULT curdate(),
  `updated_at` DATE NOT NULL DEFAULT curdate(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hyo_project_db`.`schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyo_project_db`.`schedule` ;

CREATE TABLE IF NOT EXISTS `hyo_project_db`.`schedule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `schedule_type` ENUM('NORMAL', 'PROJECT') NOT NULL,
  `is_public` TINYINT(1) NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  `generation_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `generation_id` (`generation_id` ASC) VISIBLE,
  CONSTRAINT `schedule_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `hyo_project_db`.`user` (`id`),
  CONSTRAINT `schedule_ibfk_2`
    FOREIGN KEY (`generation_id`)
    REFERENCES `hyo_project_db`.`generation` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 66
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hyo_project_db`.`track_project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyo_project_db`.`track_project` ;

CREATE TABLE IF NOT EXISTS `hyo_project_db`.`track_project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `objective` TEXT NOT NULL,
  `description` TEXT NOT NULL,
  `user_id` INT NOT NULL,
  `generation_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT '0',
  `thumbnail` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_track_project_title` (`title` ASC, `generation_id` ASC, `created_at` ASC) VISIBLE,
  INDEX `idx_track_project_user` (`user_id` ASC, `generation_id` ASC, `created_at` ASC) VISIBLE,
  INDEX `track_project_ibfk_2` (`generation_id` ASC) VISIBLE,
  CONSTRAINT `track_project_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `hyo_project_db`.`user` (`id`),
  CONSTRAINT `track_project_ibfk_2`
    FOREIGN KEY (`generation_id`)
    REFERENCES `hyo_project_db`.`generation` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 42
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hyo_project_db`.`track_excluded_member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyo_project_db`.`track_excluded_member` ;

CREATE TABLE IF NOT EXISTS `hyo_project_db`.`track_excluded_member` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `project_id` (`project_id` ASC) VISIBLE,
  CONSTRAINT `track_excluded_member_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `hyo_project_db`.`user` (`id`),
  CONSTRAINT `track_excluded_member_ibfk_2`
    FOREIGN KEY (`project_id`)
    REFERENCES `hyo_project_db`.`track_project` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hyo_project_db`.`track_team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyo_project_db`.`track_team` ;

CREATE TABLE IF NOT EXISTS `hyo_project_db`.`track_team` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `generation_id` INT NOT NULL,
  `track_project_id` INT NOT NULL,
  `is_completed` TINYINT(1) NOT NULL DEFAULT '0',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `track_project_id` (`track_project_id` ASC) VISIBLE,
  INDEX `track_team_ibfk_1` (`generation_id` ASC) VISIBLE,
  CONSTRAINT `track_team_ibfk_1`
    FOREIGN KEY (`generation_id`)
    REFERENCES `hyo_project_db`.`generation` (`id`),
  CONSTRAINT `track_team_ibfk_2`
    FOREIGN KEY (`track_project_id`)
    REFERENCES `hyo_project_db`.`track_project` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 41
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hyo_project_db`.`track_project_board`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyo_project_db`.`track_project_board` ;

CREATE TABLE IF NOT EXISTS `hyo_project_db`.`track_project_board` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `track_project_id` INT NOT NULL,
  `track_team_id` INT NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `user_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT '0',
  `thumbnail` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `track_project_id` (`track_project_id` ASC) VISIBLE,
  INDEX `track_team_id` (`track_team_id` ASC) VISIBLE,
  INDEX `idx_track_project_board_title` (`title` ASC, `user_id` ASC, `created_at` ASC) VISIBLE,
  INDEX `idx_track_project_board_user` (`user_id` ASC, `created_at` ASC) VISIBLE,
  CONSTRAINT `track_project_board_ibfk_1`
    FOREIGN KEY (`track_project_id`)
    REFERENCES `hyo_project_db`.`track_project` (`id`),
  CONSTRAINT `track_project_board_ibfk_2`
    FOREIGN KEY (`track_team_id`)
    REFERENCES `hyo_project_db`.`track_team` (`id`),
  CONSTRAINT `track_project_board_ibfk_3`
    FOREIGN KEY (`user_id`)
    REFERENCES `hyo_project_db`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 39
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hyo_project_db`.`track_team_member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyo_project_db`.`track_team_member` ;

CREATE TABLE IF NOT EXISTS `hyo_project_db`.`track_team_member` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `track_team_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `role` ENUM('LEADER', 'MEMBER') NULL DEFAULT 'MEMBER',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_track_team_member` (`track_team_id` ASC, `user_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `track_team_member_ibfk_1`
    FOREIGN KEY (`track_team_id`)
    REFERENCES `hyo_project_db`.`track_team` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `track_team_member_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `hyo_project_db`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 85
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hyo_project_db`.`web_guide`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyo_project_db`.`web_guide` ;

CREATE TABLE IF NOT EXISTS `hyo_project_db`.`web_guide` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `user_id` INT NOT NULL,
  `generation_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT '0',
  `thumbnail` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `generation_id` (`generation_id` ASC) VISIBLE,
  INDEX `idx_web_guide_title` (`title` ASC, `generation_id` ASC, `created_at` ASC) VISIBLE,
  INDEX `idx_web_guide_user` (`user_id` ASC, `generation_id` ASC, `created_at` ASC) VISIBLE,
  CONSTRAINT `web_guide_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `hyo_project_db`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hyo_project_db`.`web_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyo_project_db`.`web_image` ;

CREATE TABLE IF NOT EXISTS `hyo_project_db`.`web_image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `web_id` INT NOT NULL,
  `image_path` VARCHAR(255) NOT NULL,
  `created_at` DATE NOT NULL DEFAULT curdate(),
  `updated_at` DATE NOT NULL DEFAULT curdate(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hyo_project_db`.`web_recommend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyo_project_db`.`web_recommend` ;

CREATE TABLE IF NOT EXISTS `hyo_project_db`.`web_recommend` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `user_id` INT NOT NULL,
  `generation_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT '0',
  `url_deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_active_url` (`url` ASC, `url_deleted_at` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `generation_id` (`generation_id` ASC) VISIBLE,
  CONSTRAINT `web_recommend_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `hyo_project_db`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 85
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hyo_project_db`.`youtube`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hyo_project_db`.`youtube` ;

CREATE TABLE IF NOT EXISTS `hyo_project_db`.`youtube` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `video_id` VARCHAR(50) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `channel` VARCHAR(255) NOT NULL,
  `generation_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `video_id` (`video_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
